db/models.js

(feat) Adds Instance, Instances and User models

---

db/db.js
db/models.js
package.json
server/helpers.js

(feat) completes delete server route and corresponding helper function

---

server/helpers.js

(feat) Adds POST helper function

---

db/db.js
db/models.js
server/helpers.js
server/routes.js

(feat) Updates habits in db on PUT request to /habits/:habitid

---

db/models.js
server/helpers.js
server/routes.js

(feat) Creates new instances of a habit

---

db/models.js
server/helpers.js

(feat) adds auto-updating instanceCount property to habit db model

---

app/components/Inbox.js
app/containers/InboxContainer.js

(feat) Deletes habits from db and view when delete swipe pressed

---

app/components/Inbox.js
app/containers/InboxContainer.js
package.json

Closes #32 
Fixes infinite getHabits() calls.

(feat) Creates new habit instances

---

app/components/Create.js
app/components/Inbox.js
app/components/Welcome.js
app/containers/AppContainer.js
app/containers/CreateContainer.js
app/containers/InboxContainer.js
app/containers/LoadingContainer.js

- Upon habit edit click, user is brought back to `AddHabit` view with fields populated with habit details (can actually be edited)
- Nav bar title changes to 'Edit Habit'
- Confirmation alert now dynamic. Prints 'Habit updated!' upon submitting an edit
- `Welcome` view title changed to 'Better'
- Removes back/forward buttons in views
- 'Inbox' removed from `Welcome` view
- 'Back' removed from `AddHabit` view
- 'Back' removed from `Inbox` view
- Adds several comments
- Closes #33

(feat) Adds editing of habits

---

server/helpers.js

strings are then parsed server-side and sent to db as numbers (closes #49)

(fix) allows updates to goal field to be sent to the server as strings

---

app/components/Create.js
app/containers/CreateContainer.js
app/containers/InboxContainer.js
package.json

- Adds `react-native-radio-buttons` package
- Converts 'Frequency' input field into 'segmented control'

(refactor) Changes Frequency in AddHabit to segmented control

---

.travis.yml
_.travis.yml
db/db.js
db/models.js
package.json
server/helpers.js
server/routes.js
server/server.js
test/DbSpec.js
test/ServerSpec.js

- Separates dev dependencies in `package.json`
- Installs `supertest` (which allows `node server.js` to be removed from `npm test` script)
- Adds `process.env.NODE_ENV` to spec files, `server.js`, `routes.js`, and `db.js` to suppress logging when running tests
- Verified app still working properly
- Removes underscore from `.travis.yml` file and adds command to install npm v3

(test) Refactors ServerSpec.js to focus less on database interactions

---

package.json
test/DbSpec.js
test/ServerSpec.js

- Moves `morgan` middleware into dependencies from devDependencies in `package.json`
- Refactors `beforeEach` in `ServerSpec.js`

(test) Begins testing helper functions

---

.babelrc
app/components/Create.js
app/containers/CreateContainer.js
package.json
setup.js
test/ClientSpec.js

Closes #71 
-Adds test dependencies
-enzyme
-jsdom (mount working in one of client tests)
-react-dom
-react-native-mock
-react-addons-test-utils
-Adds tests for Loading, Create components and CreateContainer

(test) Adds client tests

---

.gitignore
app/containers/AppContainer.js
app/containers/InboxContainer.js

- User is redirected to login when logout button is pressed
- Does not log user out of Auth0

(feat) Adds logout

---

app/actions/inboxActions.js
app/containers/AppContainer.js
app/containers/CreateContainer.js
app/containers/InboxContainer.js
app/containers/LoadingContainer.js
index.ios.js
server/helpers.js
server/routes.js

* Changes /habits to /habits/:user
* Changes /habits/:habitid to /habits/:user/:habitid
* Correctly saves new users to DB
* Adds new habits to correct user
* Deletes habits from correct user
* Gets habits per user

(refactor) Begins DB refactor to account for users

---

app/containers/CreateContainer.js
db/models.js
server/helpers.js
server/routes.js

1. `CreateContainer.js`
- Removes commented, unused fields in habits
2. `models.js`
- Adds `habitsSchema` which replaces `habits` array in `User` model
- Removes `unit`, `currentGoal`, and `schedule` fields from `Habit` model
- Removes Mongoose middleware
3. `helpers.js` and `routes.js`
- Refactors all helpers and some routes to reflect changes made in `models.js`

Refactors helpers.js

---

app/components/HabitDetails.js
app/components/HabitSettings.js
app/containers/AppContainer.js
app/containers/InboxContainer.js

-Navigation routes to HabitSettings and HabitDetails have not been added
-Set initalRoute in AppContainer to HabitSetting/HabitDetails to view rendered components

(feat) Adds skeleton of HabitSettings and HabitDetails views

---

server/helpers.js
server/routes.js
test/ServerSpec.js

1. `helpers.js`
- `addHabits`
- Adds manual error checking for updates missing any required fields
- Removes one of four success 'then' functions
- `return newHabit.save()` was returning undefined and not sending the newly created habit
- Moves `Instances` creation up
2. `routes.js`
- Removes redundant GET handler to `/user` path
3. `ServerSpec.js`
- Adds user creation and removal to before/afterEach functions
- Updates route and status code changes
4. Closes #65 and #67

Refactors Basic Server Tests

---

app/components/HabitDetails.js
app/components/HabitSettings.js
app/containers/AppContainer.js

1. `HabitDetails.js`
- Minor spacing cleanup
2. `HabitSettings.js`
- Comments out editing mode (temporary)
- Aligns 'Reminder' and switch horizontally into a row
- Toggling renders date picker

Adds basic Habit Settings view

---

app/components/HabitSettings.js
app/components/Inbox.js
app/containers/AppContainer.js
app/containers/InboxContainer.js
index.ios.js
ios/thesis.xcodeproj/project.pbxproj
ios/thesis/AppDelegate.m
ios/thesis/Info.plist

* Tapping habit name or count navigates to habit details
* Slider on habit allows navigating to edit habit

(refactor) Changes inbox navigation

---

app/components/Create.js
index.ios.js
server/helpers.js
server/routes.js
test/ClientSpec.js
test/DbSpec.js
test/ServerSpec.js

* Changes error handling on all server routes from callbacks to promises
* Corrects server tests to account for error handling refactor
* Corrects DB tests to account for error handling refactor
* Corrects client tests to account for removal of frequency

(refactor) Uses promises for all server error handling

---

app/components/Create.js
app/components/HabitSettings.js
app/components/Welcome.js
package.json

Uses Button component from react-native-button module

(style) adds new styles for buttons and input fields

---

app/components/HabitDetails.js
app/containers/AppContainer.js
app/lib/calendar.js
package.json
server/helpers.js
server/routes.js
setup.js

Closes #144 
- Adds server route and database helper to retrieve instances of a habit with habitID
- Adds helpers in app/lib/calendar.js for calendar functionality in habit details

(feat) Adds habit details calendar functionality

---

app/components/HabitDetails.js
app/components/Note.js
db/models.js
index.ios.js
server/helpers.js
server/routes.js

- Adds GET server route and database helper to retrieve habit instance by instanceId
- Adds PUT server route and database helper to edit habit instance by instanceId

(feat) Adds notes to habit instances

---

app/components/HabitDetails.js
app/containers/AppContainer.js
app/containers/InboxContainer.js
app/containers/ProfileContainer.js
server/routes.js

1. `AppContainer.js`
- Adds `configureScene` function to `Navigator` component to improve scene transitions
2. Adjusts spacing and removes console.logs
- `HabitDetails.js`
- `InboxContainer.js`
- `ProfileContainer.js`
- `routes.js`
Closes #136

(fix) Improves scene transitions

---

app/components/Profile.js
app/containers/ProfileContainer.js
server/helpers.js
server/routes.js

1. `Profile.js`
- Adds `userName`, `photo`, and `this.props.user.badges` to initial state
- Renders user photo (there is a default provided by Auth0 even for non-facebook/google users) and username
- Adds styling
2. `ProfileContainer.js`
- Passes `profile` and `user` objects to Profile component
3. `helpers.js`
- Adds username to `addUser`
4. `routes.js`
- Parses username from request body and passes it to `helpers.addHabit` in '/user' POST handler

(feat) Additions to user profile

---

app/components/Profile.js
app/containers/CreateContainer.js
app/containers/InboxContainer.js
app/containers/ProfileContainer.js
index.ios.js
server/badges.js
server/helpers.js
server/routes.js

* Refactors route and helpers for get and update user to /user/:email 
* Fixes badges not displaying properly in profile after they have been earned elsewhere
* Converts toast arrays to string so that alert displays properly when badge is earned

(feat) Implements recently earned badges in profile view

---

app/components/Inbox.js
app/containers/AppContainer.js
app/containers/InboxContainer.js
index.ios.js

1.  `InboxContainer.js` & `Inbox.js`
- Changes new habit button text from "New" to plus icon
- Increases size of new habit button
- Prevents scrolling inbox while swipe menu is swiped out
- Reverts RefreshableListView to ListView for inbox habits display
2. `AppContainer.js`
- Changes navigator transition to use FadeAndroid
Closes #135

(refactor) Navigation refactors on habits inbox and nav transitions

---

app/components/Welcome.js
app/containers/AppContainer.js
app/containers/CreateContainer.js
index.ios.js

(refactor) Hides tab bar nav during onboarding

---

README.md

Followed the following guide to add the demo gif to the README file:
http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

(chore) Adds demo gif to README
